"""Render a *runnable* Semaphore stack + a catalog-driven fleet, from a catalog.

This is the heaviest surface: instead of only emitting config, it emits files an
operator can ``docker compose up`` to get a working Semaphore (MIT) fronting the
``local81`` CLI, backed by PostgreSQL 17 — plus a friendly static launcher page
and the 10-host demo fleet compose, both generated from the same catalog.

Still pure: it returns ``{relative_path: text}`` and writes nothing itself, and
it never bakes a secret literal — every credential is a ``${PLACEHOLDER}`` the
operator feeds from a secret reference via ``.env``.
"""

from __future__ import annotations

from ..recipes import Catalog


def render_stack(
    catalog: Catalog,
    *,
    db_password_ref: str,
    image: str = "semaphoreui/semaphore:latest",
    pg_image: str = "postgres:17",
    semaphore_port: int = 3000,
) -> dict[str, str]:
    """Return the file tree (path -> contents) for a runnable Semaphore stack."""
    files: dict[str, str] = {}
    files["docker-compose.semaphore.yml"] = _semaphore_compose(image, pg_image, semaphore_port)
    files[".env.example"] = _env_example(db_password_ref)
    files["launcher.html"] = _launcher_html(catalog, semaphore_port)
    files["import.sh"] = _import_script(catalog, semaphore_port)
    files["fleet/docker-compose.fleet.yml"] = _fleet_compose(catalog)
    files["fleet/Dockerfile.role"] = _fleet_dockerfile(catalog)
    files["README.md"] = _stack_readme(catalog, semaphore_port)
    return files


def _semaphore_compose(image: str, pg_image: str, port: int) -> str:
    return f"""# Runnable Semaphore stack — generated by `local81 ui stack-render`.
# `docker compose -f docker-compose.semaphore.yml --env-file .env up -d`
# Semaphore (MIT) fronts the local81 CLI; PostgreSQL 17 is its backing store.
# No secret literals live here — fill .env from your secret references first.
name: local81-semaphore

services:
  postgres:
    image: {pg_image}
    environment:
      POSTGRES_DB: semaphore
      POSTGRES_USER: semaphore
      POSTGRES_PASSWORD: ${{SEMAPHORE_DB_PASSWORD:?set SEMAPHORE_DB_PASSWORD in .env}}
    volumes:
      - semaphore-pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U semaphore"]
      interval: 5s
      timeout: 5s
      retries: 10

  semaphore:
    image: {image}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "{port}:3000"
    environment:
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB_HOST: postgres
      SEMAPHORE_DB_PORT: "5432"
      SEMAPHORE_DB: semaphore
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: ${{SEMAPHORE_DB_PASSWORD:?set SEMAPHORE_DB_PASSWORD in .env}}
      SEMAPHORE_ADMIN: ${{SEMAPHORE_ADMIN:-admin}}
      SEMAPHORE_ADMIN_NAME: ${{SEMAPHORE_ADMIN:-admin}}
      SEMAPHORE_ADMIN_EMAIL: ${{SEMAPHORE_ADMIN_EMAIL:-admin@example.com}}
      SEMAPHORE_ADMIN_PASSWORD: ${{SEMAPHORE_ADMIN_PASSWORD:?set SEMAPHORE_ADMIN_PASSWORD in .env}}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${{SEMAPHORE_ACCESS_KEY_ENCRYPTION:?set SEMAPHORE_ACCESS_KEY_ENCRYPTION in .env}}
    volumes:
      # Mount the control-node project so templates can shell out to `local81`.
      - ${{LOCAL81_DIR:-../..}}:/srv/local81:rw
    restart: unless-stopped

volumes:
  semaphore-pg:
"""


def _env_example(db_password_ref: str) -> str:
    return f"""# Copy to .env and fill from your secret references — NEVER commit real values.
# Source of truth for the DB password reference: {db_password_ref}
#
# Generate strong values, e.g.:
#   openssl rand -base64 32   # for SEMAPHORE_ACCESS_KEY_ENCRYPTION
SEMAPHORE_DB_PASSWORD=
SEMAPHORE_ADMIN=admin
SEMAPHORE_ADMIN_EMAIL=admin@example.com
SEMAPHORE_ADMIN_PASSWORD=
SEMAPHORE_ACCESS_KEY_ENCRYPTION=
# Absolute path to your local81 project (mounted into Semaphore as /srv/local81)
LOCAL81_DIR=../..
"""


def _import_script(catalog: Catalog, port: int) -> str:
    return f"""#!/usr/bin/env bash
# Best-effort: log into the running Semaphore and create the '{catalog.name}'
# project, then print the rendered templates to import. Semaphore's API surface
# varies by version, so this script favours clarity over cleverness: it gets you
# a session cookie and the project, then tells you exactly what to import.
set -euo pipefail
BASE="${{SEMAPHORE_URL:-http://localhost:{port}}}"
USER="${{SEMAPHORE_ADMIN:-admin}}"
PASS="${{SEMAPHORE_ADMIN_PASSWORD:?export SEMAPHORE_ADMIN_PASSWORD}}"
JAR="$(mktemp)"

echo ">> logging in to $BASE"
curl -fsS -c "$JAR" -H 'Content-Type: application/json' \\
  -d "{{\\"auth\\":\\"$USER\\",\\"password\\":\\"$PASS\\"}}" "$BASE/api/auth/login" >/dev/null

echo ">> creating project '{catalog.name}' (ignore error if it already exists)"
curl -fsS -b "$JAR" -H 'Content-Type: application/json' \\
  -d '{{"name":"{catalog.name}","alert":false}}' "$BASE/api/projects" || true

echo
echo ">> Templates to create are in ../semaphore/templates.json"
echo ">> Dispatcher scripts are in ../semaphore/dispatch/ (mounted at /srv/local81/.local81/ui/semaphore/dispatch)"
echo ">> Open $BASE and add a Bash task template per entry, pasting its survey_vars."
"""


def _fleet_dockerfile(catalog: Catalog) -> str:
    # Union of packages across recipes keeps one image that satisfies every role.
    pkgs: list[str] = []
    for r in catalog.recipes:
        for p in r.packages:
            if p not in pkgs:
                pkgs.append(p)
    pkg_line = " ".join(sorted(pkgs))
    return f"""# Catalog-driven fleet image ({catalog.name}) — one image, role at run time.
# Satisfies local81's only endpoint needs: sshd + python3 + rsync + find + sha256sum.
FROM debian:12-slim
RUN apt-get update && apt-get install -y --no-install-recommends \\
        {pkg_line} \\
    && rm -rf /var/lib/apt/lists/* \\
    && mkdir -p /var/run/sshd /srv/app /var/log/app \\
    && groupadd -f operator && useradd -m -s /bin/bash -g operator operator \\
    && mkdir -p /home/operator/.ssh && chmod 700 /home/operator/.ssh
ARG PUBKEY=""
RUN echo "$PUBKEY" > /home/operator/.ssh/authorized_keys \\
    && chmod 600 /home/operator/.ssh/authorized_keys \\
    && chown -R operator:operator /home/operator/.ssh /srv/app /var/log/app
EXPOSE 22
ENTRYPOINT ["/usr/sbin/sshd", "-D", "-e"]
"""


def _fleet_compose(catalog: Catalog) -> str:
    lines = [
        f"# {catalog.name} fleet — {len(catalog.recipes)} role containers, generated from the catalog.",
        "# Build the role image once, then each service runs it with its ROLE + port.",
        "#   PUBKEY=\"$(cat ~/.ssh/id_demo.pub)\" docker compose -f docker-compose.fleet.yml up -d --build",
        f"name: {catalog.name}-fleet",
        "",
        "networks:",
        f"  {catalog.name}net:",
        f"    name: {catalog.name}net",
        "",
        "services:",
    ]
    for r in catalog.recipes:
        block = [
            f"  {r.alias}:",
            "    build:",
            "      context: .",
            "      dockerfile: Dockerfile.role",
            "      args:",
            "        PUBKEY: ${PUBKEY:?export PUBKEY with your demo public key}",
            f"    image: {catalog.name}-role:latest",
            f"    container_name: {catalog.name}-{r.alias}",
            f"    hostname: {r.alias}",
            f"    environment: {{ ROLE: {r.role} }}",
            f"    ports: [\"127.0.0.1:{r.port}:22\"]",
            f"    networks: [{catalog.name}net]",
            "    restart: \"no\"",
            f"    # {r.title}  |  health: {r.health or 'n/a'}",
        ]
        lines.extend(block)
        lines.append("")
    return "\n".join(lines)


def _launcher_html(catalog: Catalog, port: int) -> str:
    """A friendly, single-file landing page — the human face of the buttons."""
    cat_cards = "\n".join(_category_card(c) for c in catalog.categories)
    group_chips = "\n".join(
        f'      <span class="chip">{g.label} <em>({len(g.members)})</em></span>'
        for g in catalog.groups
    )
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Local-81 — {catalog.name} control panel</title>
<style>
  :root {{ color-scheme: light dark; --bg:#0f1115; --card:#171a21; --ink:#e8ecf3; --mut:#9aa4b2; --acc:#4f9cff; --ok:#3fb950; }}
  * {{ box-sizing:border-box; }}
  body {{ margin:0; font:16px/1.5 ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,sans-serif; background:var(--bg); color:var(--ink); }}
  header {{ padding:32px 24px 8px; max-width:980px; margin:0 auto; }}
  h1 {{ margin:0 0 4px; font-size:26px; }}
  .sub {{ color:var(--mut); margin:0 0 20px; }}
  main {{ max-width:980px; margin:0 auto; padding:0 24px 48px; }}
  .cta {{ display:inline-block; background:var(--acc); color:#fff; text-decoration:none; padding:12px 20px; border-radius:10px; font-weight:600; }}
  .cta:hover {{ filter:brightness(1.08); }}
  .grid {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(280px,1fr)); gap:16px; margin-top:24px; }}
  .card {{ background:var(--card); border:1px solid #232733; border-radius:14px; padding:18px; }}
  .card h2 {{ margin:0 0 10px; font-size:17px; }}
  .card ul {{ margin:0; padding-left:18px; }}
  .card li {{ margin:3px 0; }}
  .card li .mut {{ color:var(--mut); }}
  .mute {{ color:var(--mut); }}
  .chips {{ margin:16px 0 0; display:flex; flex-wrap:wrap; gap:8px; }}
  .chip {{ background:#1e222b; border:1px solid #2a2f3a; border-radius:999px; padding:5px 12px; font-size:14px; }}
  .chip em {{ color:var(--mut); font-style:normal; }}
  .steps {{ counter-reset:step; list-style:none; padding:0; margin:18px 0 0; }}
  .steps li {{ counter-increment:step; margin:8px 0; padding-left:38px; position:relative; }}
  .steps li::before {{ content:counter(step); position:absolute; left:0; top:-2px; width:26px; height:26px; border-radius:50%; background:var(--acc); color:#fff; display:grid; place-items:center; font-weight:700; font-size:14px; }}
  footer {{ max-width:980px; margin:0 auto; padding:0 24px 40px; color:var(--mut); font-size:14px; }}
  code {{ background:#1e222b; padding:1px 6px; border-radius:6px; }}
</style>
</head>
<body>
<header>
  <h1>{catalog.name} &middot; control panel</h1>
  <p class="sub">{catalog.description}</p>
  <a class="cta" href="http://localhost:{port}" target="_blank" rel="noopener">Open Semaphore &rarr;</a>
  <span class="mute" style="margin-left:12px">Pick a task, fill the dropdowns, press <strong>Run</strong>.</span>
  <ol class="steps">
    <li>Open Semaphore and sign in.</li>
    <li>Choose a task below by its category — e.g. <strong>Deploy &amp; Release</strong>.</li>
    <li>Pick the <strong>Action</strong> and (for deploys) the <strong>host group</strong> from the dropdowns.</li>
    <li>Press <strong>Run</strong>. Local-81 does the rest and records a signed receipt.</li>
  </ol>
</header>
<main>
  <div class="grid">
{cat_cards}
  </div>
  <div class="chips">
    <strong style="align-self:center">Host groups:</strong>
{group_chips}
  </div>
</main>
<footer>
  Every button shells out to the <code>local81</code> CLI on the control node — the same command you could type by hand.
  Nothing here holds your target SSH keys unless you opted into Semaphore key-custody. Generated from
  <code>{catalog.source.name if catalog.source else catalog.name + '.yaml'}</code>; edit that file and re-render to change these buttons.
</footer>
</body>
</html>
"""


def _category_card(cat) -> str:
    items = "\n".join(
        f'        <li>{o.label}'
        + (' <span class="mut">&middot; changes hosts</span>' if o.mutating else "")
        + "</li>"
        for o in cat.options
    )
    return f"""    <div class="card">
      <h2>{cat.title}</h2>
      <ul>
{items}
      </ul>
    </div>"""


def _stack_readme(catalog: Catalog, port: int) -> str:
    return f"""# Runnable Semaphore stack — {catalog.name}

Generated by `local81 ui stack-render`. This stands up a real Semaphore (MIT)
web UI in front of the `local81` CLI, so a less-technical operator drives deploys
from dropdowns instead of a terminal.

## Quick start

```bash
cp .env.example .env        # then fill the blanks from your secret references
docker compose -f docker-compose.semaphore.yml --env-file .env up -d
open launcher.html          # the friendly landing page
./import.sh                 # create the project; then import templates.json in the UI
```

Semaphore comes up on <http://localhost:{port}>. The launcher page explains the
buttons; the task templates and their dropdown surveys are in
`../semaphore/templates.json`, and each one runs `../semaphore/dispatch/<category>.sh`.

## The demo fleet (optional)

`fleet/docker-compose.fleet.yml` builds the {len(catalog.recipes)} role containers this
catalog describes, so you have something real to deploy to:

```bash
PUBKEY="$(cat ~/.ssh/id_demo.pub)" \\
  docker compose -f fleet/docker-compose.fleet.yml up -d --build
```

## Honesty notes

- No secret literals are written here — `.env` placeholders are filled from your
  secret references at runtime, keeping local81's secrets-never-at-rest posture.
- Default key custody is `local81` (Semaphore holds no target SSH creds). Using
  Semaphore's native Key Store is gated and raises compliance finding L26-UI-001.
- Mutating actions (deploy, rollback) are labelled in the launcher; they change
  target state, the rest are read-only.
"""
