#!/usr/bin/env python3
"""Local-81 RECIPE — onboard endpoints (EPs) from a simple CSV.

Reads a space-separated file of endpoints:

    # hostname  ip  group  purpose
    web01   10.0.0.11  web-tier   nginx-frontend
    papi01  10.0.0.21  api-tier   python-api
    pgdb01  10.0.0.31  data-tier  postgres-17

and projects it into the inputs the *existing* Local-81 onboarding commands
consume — nothing here contacts a host. It emits, into an output dir:

  * ssh_config        — one ``Host`` block per EP (name -> ip), append to ~/.ssh/config
  * hosts.txt         — one hostname per line, for ``local81 onboard --hosts-file``
  * groups.txt        — group -> members, human-readable (the "which hosts" map)
  * fleet.yaml        — a validated ``local81.recipes.v1`` catalog (groups + one
                        recipe per EP, role=purpose), so the same fleet drives
                        ``ui semaphore-render`` / ``ui n8n-render`` / deploy.

Then you run the real onboarding (dry-run first, --execute to act):

    local81 keys ensure --execute
    local81 onboard --hosts-file <out>/hosts.txt            # plan + read-only sweep
    local81 onboard --hosts-file <out>/hosts.txt --execute  # gen+copy key, sweep
    local81 doctor --fleet

Strict + fail-closed: malformed rows, duplicate hostnames, or duplicate IPs are
errors, never silently dropped — the same posture doctor/deploy --check take.
Stdlib only.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_NAME_RE = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9._-]*$")
_IP_RE = re.compile(r"^\d{1,3}(\.\d{1,3}){3}$")  # IPv4; hostnames also allowed in the ip column


class OnboardError(Exception):
    """The endpoints file is missing, malformed, or internally inconsistent."""


def _slug(s: str) -> str:
    """A catalog-safe key/alias: lowercase, alnum + dash."""
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-") or "ep"


def parse(path: Path) -> list[dict]:
    if not path.exists():
        raise OnboardError(f"endpoints file not found: {path}")
    rows: list[dict] = []
    seen_host: dict[str, int] = {}
    seen_ip: dict[str, int] = {}
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) < 4:
            raise OnboardError(
                f"{path}:{lineno}: need 4 fields 'hostname ip group purpose', got {len(parts)}: {raw!r}"
            )
        host, ip, group, *purpose_parts = parts
        purpose = " ".join(purpose_parts)
        if not _NAME_RE.match(host):
            raise OnboardError(f"{path}:{lineno}: invalid hostname {host!r}")
        if not (_IP_RE.match(ip) or _NAME_RE.match(ip)):
            raise OnboardError(f"{path}:{lineno}: invalid ip/address {ip!r}")
        if host in seen_host:
            raise OnboardError(f"{path}:{lineno}: duplicate hostname {host!r} (also line {seen_host[host]})")
        if ip in seen_ip:
            raise OnboardError(f"{path}:{lineno}: duplicate ip {ip!r} (also line {seen_ip[ip]})")
        seen_host[host] = lineno
        seen_ip[ip] = lineno
        rows.append({"host": host, "ip": ip, "group": group, "purpose": purpose})
    if not rows:
        raise OnboardError(f"{path}: no endpoints found (all blank/comment)")
    return rows


def render_ssh_config(rows: list[dict], user: str, identity: str) -> str:
    out = ["# Generated by local81 onboard_from_csv.py — append to ~/.ssh/config", ""]
    for r in rows:
        out += [
            f"Host {r['host']}",
            f"    HostName {r['ip']}",
            f"    User {user}",
            f"    IdentityFile {identity}",
            "    StrictHostKeyChecking accept-new",  # first connect won't block; pin keys after onboarding
            "",
        ]
    return "\n".join(out)


def render_hosts(rows: list[dict]) -> str:
    return "\n".join(r["host"] for r in rows) + "\n"


def render_groups(rows: list[dict]) -> str:
    groups: dict[str, list[str]] = {}
    for r in rows:
        groups.setdefault(r["group"], []).append(r["host"])
    lines = ["# group -> members (use with: local81 onboard --hosts <comma,list>)"]
    for g, members in sorted(groups.items()):
        lines.append(f"{g}: {','.join(members)}")
    return "\n".join(lines) + "\n"


def render_catalog(rows: list[dict], name: str, base_port: int) -> str:
    """A valid local81.recipes.v1 catalog. Ports are placeholders (unique,
    sequential from base_port) — edit to the EP's real service port."""
    groups: dict[str, list[str]] = {}
    for r in rows:
        groups.setdefault(r["group"], []).append(_slug(r["host"]))
    L = [
        "# Generated by local81 onboard_from_csv.py — a fleet catalog for your EPs.",
        "# Drives:  local81 ui semaphore-render / ui n8n-render / deploy.",
        "# NOTE: ports are unique placeholders — set each to the EP's real service port.",
        "schema: local81.recipes.v1",
        f"name: {name}",
        f"description: Endpoints onboarded from CSV ({len(rows)} hosts).",
        "",
        "categories:",
        "  - key: deploy",
        "    title: Deploy & Release",
        "    options:",
        '      - { key: plan,    label: "Plan — preview", command: "plan --summary" }',
        '      - { key: dryrun,  label: "Dry-run",        command: "deploy --latest --dry-run --forks {forks}" }',
        '      - { key: execute, label: "Deploy",         command: "deploy --latest --forks {forks}", mutating: true }',
        "  - key: observe",
        "    title: Observe",
        "    options:",
        '      - { key: doctor, label: "Fleet readiness", command: "doctor --fleet" }',
        '      - { key: status, label: "Status",          command: "status" }',
        "",
        "parameters:",
        "  - { key: forks, type: int, default: 5 }",
        "",
        "groups:",
    ]
    for g, members in sorted(groups.items()):
        L.append(f'  - {{ key: {_slug(g)}, label: "{g}", members: [{", ".join(members)}] }}')
    L += ["", "recipes:"]
    for i, r in enumerate(rows):
        L += [
            f"  - key: {_slug(r['host'])}",
            f"    title: {r['host']} ({r['purpose']})",
            f"    role: {_slug(r['purpose'])}",
            f"    alias: {r['host']}            # ssh alias -> {r['ip']}",
            f"    port: {base_port + i}",
            f"    group: {_slug(r['group'])}",
            "    build: { base: debian:12-slim, packages: [], workload: '' }",
            "    deploy: { target_dir: /srv/app }",
            "    health: { command: '' }",
            "    test: { probe: '' }",
        ]
    return "\n".join(L) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Onboard endpoints from a space-separated CSV into Local-81 inputs.")
    ap.add_argument("csv", help="endpoints file: 'hostname ip group purpose' per line")
    ap.add_argument("--out", default="onboarding-out", help="output directory (default: ./onboarding-out)")
    ap.add_argument("--user", default="operator", help="SSH login user for the EPs (default: operator)")
    ap.add_argument("--identity", default="~/.ssh/id_ed25519", help="control-node private key path")
    ap.add_argument("--fleet-name", default="endpoints", help="catalog name")
    ap.add_argument("--base-port", type=int, default=9000, help="first placeholder port for the catalog")
    args = ap.parse_args(argv)

    try:
        rows = parse(Path(args.csv))
    except OnboardError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    (out / "ssh_config").write_text(render_ssh_config(rows, args.user, args.identity), encoding="utf-8")
    (out / "hosts.txt").write_text(render_hosts(rows), encoding="utf-8")
    (out / "groups.txt").write_text(render_groups(rows), encoding="utf-8")
    (out / "fleet.yaml").write_text(render_catalog(rows, args.fleet_name, args.base_port), encoding="utf-8")

    ngroups = len({r["group"] for r in rows})
    print(f"Parsed {len(rows)} endpoint(s) in {ngroups} group(s). Wrote to {out}/:")
    for f in ("ssh_config", "hosts.txt", "groups.txt", "fleet.yaml"):
        print(f"  - {out / f}")
    print("\nNext (dry-run first, then --execute):")
    print(f"  cat {out}/ssh_config >> ~/.ssh/config")
    print(f"  local81 keys ensure --execute")
    print(f"  local81 onboard --hosts-file {out}/hosts.txt           # plan + read-only sweep")
    print(f"  local81 onboard --hosts-file {out}/hosts.txt --execute # gen+copy key, then sweep")
    print(f"  local81 doctor --fleet")
    print(f"  local81 ui semaphore-render --catalog {out}/fleet.yaml --db-host <pg>  # optional: drive the UI")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
